"""empty message

Revision ID: d7b32aa51cec
Revises: 4faf6fd57d06
Create Date: 2021-03-05 21:53:03.714687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b32aa51cec'
down_revision = '4faf6fd57d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('info_type', sa.String(length=20), nullable=True))
    op.add_column('planet', sa.Column('info_type', sa.String(length=20), nullable=True))
    op.add_column('vehicle', sa.Column('info_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'info_type')
    op.drop_column('planet', 'info_type')
    op.drop_column('characters', 'info_type')
    # ### end Alembic commands ###
